### ISSUE TITLE
MEDIA_ROOT is not properly set when running in development env (local) 

### ISSUE THREAD

**Issue by vladox** [divio/aldryn-django#256]
We have just discovered a bug in aldryn_config for aldryn_django in the latests version > 3

when running locally in the line 395 `dsn.path = settings['MEDIA_ROOT']`, `MEDIA_ROOT` is always an empty string
apparently `MEDIA_ROOT` gets properly set just on line 426: `settings['MEDIA_ROOT'] = env('MEDIA_ROOT', os.path.join(settings['DATA_ROOT'], 'media'))`
The issue is that locally no media can be located due to an invalid media path

**Comment by kinkerl** [comment]
PR merged. Thanks!
It will be rolled out with the next release!
