### ISSUE TITLE
MEDIA_URL not working

### ISSUE THREAD

**Issue by petrklus** [divio/aldryn-django#264]
It seems that the `MEDIA_URL` is always set to `/media/` - https://github.com/divio/aldryn-django/blob/support/3.2.x/aldryn_config.py#L405

This only really works on local machine, as any storage with a different URL is incorrect.

This can be resolved by explicitly setting an environment variable `MEDIA_URL`, though that seems like a temporary solution only.

Using Django 3.2.

**Comment by kinkerl** [comment]
Hi @petrklus
I have a hard time to figure this out. I currently think this is only an issue when doing local development and pointing a media URL to a remote URL which is specified via a storage DSN? The logic did not automatically use the value from the storage DSN and used the (wrong) default MEDIA_URL instead? Can you please elaborate how you got to this point?

**Comment by petrklus** [comment]
Hi @kinkerl , I have hit this problem during production - as I use the `MEDIA_URL` variable in one of our custom applications. We store the local file prefix in the database and then use the `settings.MEDIA_URL` as a prefix to get an absolute URL.

This worked fine in local development, however, in production it was not correctly set.

The only solution we could see was to set an explicit ENV variable `MEDIA_URL` for test/production instead of relying on automatic population (which did work in the past).

In a nutshell, I believe the issue is here - https://github.com/divio/aldryn-django/blob/support/3.2.x/aldryn_config.py#L405 - the line 407 is never reached as the `env('MEDIA_URL', '/media/')` sets the variable value in all reasonable circumstances. I suppose you could set the env variable `MEDIA_URL` to an empty string and this would have work but that does not seem reasonable.

I have logged into one of our projects on Divio (live) where we do not set the env var, and I still get an incorrect value:

<img width="538" alt="image" src="https://user-images.githubusercontent.com/1115667/164051186-dde3f23b-ce2f-4069-bbcb-f22115214fb9.png">

I would expect to see the actual CDN URL there, as there is nothing in the `/media/` on the live server.

Just to clarify - this is not causing issues with Filer or other means of including assets, as that does not use the `settings.MEDIA_URL` variable from what I can tell.

Lastly, how I got to this point - it started appearing after we upgraded from Aldryn Django 2.2 to 3.2 I believe, before that it was correctly set to the CDN URL.

The reason I suspect is that the logic is different in 2.2 - https://github.com/divio/aldryn-django/blob/support/2.2.x/aldryn_config.py#L378 - 2.2 checked for `'DEFAULT_STORAGE_DSN' in settings`, which seems more appropriate to me.

[Broken 3.2 way](https://github.com/divio/aldryn-django/blob/3.2.13.0/aldryn_config.py#L405):

        settings['MEDIA_URL'] = env('MEDIA_URL', '/media/')
        if not settings['MEDIA_URL']:
            media_url = lazy_setting(
                'MEDIA_URL',
                get_default_storage_url,
                str,
            )

[Before working 2.2 way:](https://github.com/divio/aldryn-django/blob/2.2.28.0/aldryn_config.py#L377)

        settings['MEDIA_URL'] = env('MEDIA_URL', '/media/')
        if 'DEFAULT_STORAGE_DSN' in settings:
            settings.update(parse_storage_url(settings['DEFAULT_STORAGE_DSN']))

**Comment by petrklus** [comment]
@kinkerl let me know please if the [above](https://github.com/divio/aldryn-django/issues/264#issuecomment-1102851021) makes sense or if you need any further information

**Comment by kinkerl** [comment]
@petrklus makes perfect sense... i have to think about it :smile:

**Comment by kinkerl** [comment]
@petrklus i think i have a reasonably good solution for the issue and refactored the logic:

https://github.com/divio/aldryn-django/pull/271/files

my first tests look promising and all is working as intended. do you maybe already have some remarks?

**Comment by kinkerl** [comment]
i tested the changes and they work well in my tests. merging them and releasing an alpha release for this. 

thank you again for the report!

**Comment by petrklus** [comment]
> i tested the changes and they work well in my tests. merging them and releasing an alpha release for this.
> 
> thank you again for the report!

Thank you for the fix!

**Comment by petrklus** [comment]
@kinkerl I think I am seeing an issue related to this - https://sentry.io/share/issue/2dce2adb182f4b67b351076106242dac/

It seems to happen for the very first request and then does not disappear until the same Django worker is restarted.
