### ISSUE TITLE
TypeError on first render

### ISSUE THREAD

**Issue by petrklus** [divio/aldryn-django#275]
After upgrading to latest version of Aldryn Django (3.2.14.0), every first render for a web worker is as follows:

![image](https://user-images.githubusercontent.com/1115667/177368092-b76fc400-85e7-4f7e-83ba-c44d507fc516.png)

Sentry link:

https://sentry.io/share/issue/7bbc7dd4464b484bb032765268c24fda/

This has been reproduced both on real projects, as well as a freshly created project on Divio with the following Addons:

![image](https://user-images.githubusercontent.com/1115667/177368204-2fb35a07-dc7b-4de3-a9bb-2629db36d561.png)

@kinkerl I belive this is related to the recent MEDIA_URL changes, as discussed in https://github.com/divio/aldryn-django/issues/264

**Comment by petrklus** [comment]
@kinkerl I would be happy to share the Divio project that makes it easy to reproduce the issue.

**Comment by petrklus** [comment]
I suspect that the issue may be with the `lazy_setting` that is not there during the first render

**Comment by FinalAngel** [comment]
@petrklus is this still an issue?

**Comment by petrklus** [comment]
No, this is not present in 3.2 (not tested 4.2 thoroughly)
