### ISSUE TITLE
MEDIA_URL not set correctly

### ISSUE THREAD

**Issue by petrklus** [divio/aldryn-django#317]
After upgrading to Aldryn Django 4.2.9, we are seeing issues with `MEDIA_URL` not being set.

Looking at the code, this seems to be a regression as the function is working correctly on Aldryn Django 3.2.23.

Relevant portion of the code for the 3.2 version:

https://github.com/divio/aldryn-django/blob/3.2.23.0/aldryn_config.py#L398

The above has been fixed in version 3.2.14.0, via commit https://github.com/divio/aldryn-django/commit/c11004a667a43fcbc44a3fad704093883919f50a.

It seems that the 4.2.9 version is using the old&broken MEDIA_URL logic: https://github.com/divio/aldryn-django/blob/4.2.9/aldryn_config.py#L407

I believe the same logic as it's in use since 3.2.14 should work for the 4.2 branch.

**Comment by FinalAngel** [comment]
@petrklus I think this has been fixed with https://github.com/divio/aldryn-django/pull/318
