### ISSUE TITLE
easy-thumbnail==2.2.1.1 requirement is not met

### ISSUE THREAD

**Issue by marinalan** [divio/aldryn-django#78]
When i attempt to do:

pip install git+https://github.com/aldryn/aldryn-django.git@support/1.8.x
i get message:

Collecting easy-thumbnails==2.2.1.1 (from aldryn-django==1.8.16.0)
  Could not find a version that satisfies the requirement easy-thumbnails==2.2.1.1 (from aldryn-django==1.8.16.0) (from versions: 1.0a2, 1.0a3, 1.0a4, 1.0a5, 1.0a6, 1.0a7, 1.0a8, 1.0a9, 1.0a10, 1.0a11, 1.0a12, 1.0a13, 1.0a14, 1.0a15, 1.0a16, 1.0a17, 1.0a18, 1.0a19, 1.0a20, 1.0a21, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.1, 1.2, 1.3, 1.4, 1.5, 2.0, 2.0.1, 2.1, 2.2, 2.2.1, 2.3)
No matching distribution found for easy-thumbnails==2.2.1.1 (from aldryn-django==1.8.16.0)

**Comment by jmelett** [comment]
@marinalan Are you installing this on Aldryn? 2.2.1.1 is IIRC an internal release (available on our internal DevPI server only).

Also, why are you not simply using the Django package from PyPI? :)
