### ISSUE TITLE
TIME_ZONE configuration is not working

### ISSUE THREAD

**Issue by stefanfoulis** [divio/aldryn-django#79]
* The method in aldryn_config.py that sets ``TIME_ZONE`` from an env var is never called.

* ``USE_TZ`` is never set to ``True``: how should we handle backwards compatibility?

**Comment by tadeo** [comment]
Consider taking a look into https://docs.djangoproject.com/en/1.8/ref/settings/#time-zone mention of the os.environ['TZ'] variable
