### ISSUE TITLE
Please update to Latest Django 1.11.x for djangoCMS 3.4.5

### ISSUE THREAD

**Issue by vinitkumar** [divio/aldryn-django#95]
Hi, Please update the dependency to support Django 1.11. I am trying to upgrade to latest django and djangoCMS and only because of aldryn-django, it is getting blocked. Please update it as soon as possible.

**Comment by lizkepner** [comment]
I'm assuming that since most of this repo is 2 years old, there has been no development on this? Python 3.x is also not supported, and we don't start new projects in anything less than Python 3 and Django 1.10.x or Django 1.11.x anymore.
